Repository hcsp/stream-in-action, pull requests merged in 2019-10, with the labels that each got.

#11 There is a bug in problem6 。
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: is:answer

#13 Stream in action.
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#14 stream
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#12 Problem6 class Main method call filterThenConcat() method.
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: is:enhancement

#15 stream
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#16 Dev hjx
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#18 debug
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#19 通过Stream完成。
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#20 stream in action
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#21 ok
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: is:answer

#22 Java Stream
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#23 懵懵懂懂
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#24 practise java8 stream
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer
