Repository hcsp/stream-in-action, pull requests merged in 2019-09, with the labels that each got.

#5 stream practice
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#6 使用Stream简化代码
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#7 stream test
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: is:answer

#8 Add main method in Problem5
  src/main/java/com/github/hcsp/stream/Problem5.java
Labels: is:enhancement

#9 finish Stream practices
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: from:VIP, is:answer

#10 test
  src/main/java/com/github/hcsp/stream/Problem1.java
  src/main/java/com/github/hcsp/stream/Problem2.java
  src/main/java/com/github/hcsp/stream/Problem3.java
  src/main/java/com/github/hcsp/stream/Problem4.java
  src/main/java/com/github/hcsp/stream/Problem5.java
  src/main/java/com/github/hcsp/stream/Problem6.java
Labels: is:answer
